### ISSUE TITLE
sys_load_monitor_init重复初始化导致异常

### ISSUE THREAD

**Issue by HikerPan** [RT-Thread-packages/logmgr#5]
您好！
发现，默认情况下，logmgr使用sys load monitor时会会异常挂起。
经过查看代码发现
logmgr以及sys load中均调用sys_load_monitor_init进行了初始化，导致异常挂起。
实际使用中我注释掉sys load中的初始化后没有再出现异常
建议取消logmgr中的sys_load_monitor_init初始化

**Comment by armink** [comment]
方便提交一个 PR 上来吗？

**Comment by Lawlieta** [comment]
sys_load_monitor 软件包中已经添加了重复初始化功能支持，可以看一下这个 PR https://github.com/armink-rtt-pkgs/sys_load_monitor/pull/1/files

确定一下你现在使用的 sys_load_monitor 软件包是否是最新版本，最新版本应该不会有该问题
